### ISSUE TITLE
Ядра

### ISSUE THREAD

**Issue by Kolyakot33** [cubelius/minecraft-server-optimization#2]
Почему нужно использовать Airplane, а не, допустим purpur? Чем плох Paper?
Я думаю об этом следует написать.

**Comment by cubelius** [comment]
Purpur начал выходить с версии 1.14, а Airplane с 1.16.5. Purpur не является форком Airplane, хоть и содержит некоторые патчи от них, что довольно странно. Первее появился Purpur, соответственно он и старее, чем Airplane.

**Comment by cubelius** [comment]
Даже во многих вкладках с выбором ядра тебе будет показываться так: Spigot, Paper, Tuinity, **Purpur**, а уже потом **Airplane**.

![firefox_WNGVSKkNQR](https://user-images.githubusercontent.com/74359983/136677884-51d1a6c9-d90d-452a-a258-2f38a2075f59.png)

**Comment by Kolyakot33** [comment]
Да, скорее всего так, они (разработчики) всех запутали передачей патчей туда и обратно.
